version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/django
    overwrite: true
hooks:
  BeforeInstall:
    - location: /install_dependencies
      timeout: 30
      runas: root
    - location: /start_server
      timeout: 30
      runas: root
  AfterInstall:
    -location : /after_install
  ApplicationStop:
    - location: /stop_server
      timeout: 30
      runas: root
